### ISSUE TITLE
Scroll Up Indicator is shown

### ISSUE THREAD

**Issue by leonschwanitz** [gonuit/flutter-custom-refresh-indicator#18]
Hey,
when i use this code:
https://pastebin.com/cj621P44
the indicator is shown as a black circle. Is anything wrong or is this a bug?

**Comment by gonuit** [comment]
Hey @leonschwanitz,
Tank You for opening this issue. Will look at this and come to you with an answer.

**Comment by jonascaps18** [comment]
I faced the same challenge. Kindly work on it for us.

**Comment by gonuit** [comment]
### Hi @jonascaps18 and @leonschwanitz.
First of all - sorry for the late reply 😞.

Indicator from pastebin looks as folow:
  
![image](https://user-images.githubusercontent.com/37882650/119403146-30a7d880-bcde-11eb-9e54-584a9d5854d5.png)

And yes, it is black because this code defines `Container` as a black circle. This part exactly:
```dart
decoration: BoxDecoration(
    color: Colors.black,
    shape: BoxShape.circle,
),
``` 

Let me know if this helps you a bit. If there is still something that needs clarification, or sth isn't working as it should, let me know and feel free to reopen this issue.

Have a nice day! 💪🏻
