### ISSUE TITLE
NestedScrollView + TabView + ListView bug.

### ISSUE THREAD

**Issue by HaijunWei** [gonuit/flutter-custom-refresh-indicator#34]
It is used for NestedScrollView + TabView + ListView. controller.state is easy to get stuck in dragging, causing the pull-down refresh to fail to start.
I added the first line of `_handleScrollStartNotification`, it work.
``` dart
if (controller.state == IndicatorState.dragging) {
    setIndicatorState(IndicatorState.idle);
}

// controller.state always IndicatorState.dragging, _canStart always false.
_canStart = controller.state == IndicatorState.idle &&
        (widget.reversed
            ? notification.metrics.extentAfter == 0
            : notification.metrics.extentBefore == 0);
```

Switching TabView quickly and sliding the ListView can easily trigger this problem.

**Comment by gonuit** [comment]
If you are able to provide a sample code that reproduces this problem, it will be of great help. Some GIFs or videos with this problem may also be helpful, as at the moment I don't know what exactly is going on.

I want to change the code carefully, as the suggested change might also have some implications for multiple fingers on the screen and so on.

Perhaps in your case as a solution, you can define a custom `notificationPredicate` function to filter some notifications, e.g. by depth. Or maybe you could put the indicator on each tab instead of over them 🤔
