### ISSUE TITLE
Rename 'builder' Property to 'indicatorBuilder' for Clarity

### ISSUE THREAD

**Issue by robson-rp** [gonuit/flutter-custom-refresh-indicator#45]
Hello there! I would like to suggest a minor but potentially helpful improvement to the **CustomRefreshIndicator** package. Currently, the property used to build the refresh indicator is named `builder`. To enhance clarity and make its purpose more self-explanatory, I propose renaming it to `indicatorBuilder`.

**Benefits**:
- Improved Clarity: Renaming to `indicatorBuilder` will make it instantly clear that this property is responsible for creating the custom refresh indicator.
- Better Readability: With a more descriptive name, developers will find it easier to understand and use the widget.
- Consistency: Aligning with similar properties in other Flutter widgets ensures a consistent and intuitive API design.

I believe this simple change could enhance the overall developer experience when using `CustomRefreshIndicator`. Thank you for considering this suggestion, and I'm excited to contribute to the continued improvement of the package.

Best regards.

**Comment by gonuit** [comment]
#### Hi @robson-rp! 👋🏻 
Thanks for using this package and for the suggestion 🚀.
My concern, however, is that the `builder` argument is not only responsible for rendering the indicator, but actually renders everything. This is by design as it allows you to introduce fancy animations not only for the indicator, but also for the child widget.  
With that in mind, I don't think renaming the argument from `builder` to `indicatorBuilder` would be more intuitive here. But if you have further doubts, or if you still think this is a better solution, let's reopen this topic and we can talk about it.
