### ISSUE TITLE
[Question] Default indicator

### ISSUE THREAD

**Issue by cwebbtw** [gonuit/flutter-custom-refresh-indicator#57]
Is there an out of the box icon that makes this work as a drop in replacement for the default `RefreshIndicator` flutter widget?

I'm quite happy with the flutter RefreshIndicator but would quite like to make use of the trigger options to refresh from the bottom as well as the top.

**Comment by gonuit** [comment]
### Hi @cwebbtw 👋🏻,

This is indeed something I have wanted to introduce for a long time, but have not had the time to do so. 
Now, since I have started working on the 4.0.0, this is now available on the pub.dev in the preview version [4.0.0-dev.1](https://pub.dev/packages/custom_refresh_indicator/versions/4.0.0-dev.1).

**Comment by gonuit** [comment]
### Hi @cwebbtw 👋🏻,
It is now live 🚀 . You can now use the `CustomMaterialIndicator` widget without specifying the `indicatorBuilder` argument, which will mimic the look of the built-in indicator widget. 

Here you can find a live example: [https://custom-refresh-indicator.klyta.it/#/example](https://custom-refresh-indicator.klyta.it/#/example) [[SOURCE CODE](https://github.com/gonuit/flutter-custom-refresh-indicator/blob/master/example/lib/screens/custom_material_indicator_screen.dart)]
